# Generated by Django 5.0.7 on 2024-08-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage_and_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="profile",
            name="full_name",
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name="profile",
            name="github",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website",
            field=models.URLField(),
        ),
    ]
