# Generated by Django 5.0.7 on 2024-08-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage_and_profile", "0002_alter_profile_bio_alter_profile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="full_name",
            field=models.CharField(max_length=33),
        ),
    ]
