# Generated by Django 5.0.7 on 2024-08-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage_and_profile", "0004_alter_profile_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
