# Generated by Django 5.0.7 on 2024-09-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage_and_profile", "0005_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(default="dik", max_length=50),
        ),
    ]
