# Generated by Django 5.0.7 on 2024-09-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage_and_profile", "0006_profile_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
    ]
