# Generated by Django 5.0.7 on 2024-09-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brainstorm_tools", "0002_alter_project_description_alter_project_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
