# Generated by Django 5.0.7 on 2024-09-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brainstorm_tools", "0003_alter_project_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="feature_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="subfeature",
            name="subfeature_name",
            field=models.CharField(max_length=100),
        ),
    ]
