# Generated by Django 5.0.7 on 2024-09-16 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brainstorm_tools", "0004_alter_feature_feature_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="pub_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
