# Generated by Django 5.0.7 on 2024-09-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brainstorm_tools", "0005_project_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default=models.CharField(max_length=100, unique=True), unique=True
            ),
        ),
    ]
