# Generated by Django 5.0.7 on 2024-09-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brainstorm_tools", "0007_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
