# Generated by Django 5.0.7 on 2024-09-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brainstorm_tools", "0008_alter_project_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
