# Generated by Django 5.0.7 on 2024-09-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brainstorm_tools", "0009_alter_project_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(max_length=350),
        ),
    ]
