# Generated by Django 5.0.7 on 2024-09-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brainstorm_tools", "0014_alter_project_detailed_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="detailed_description",
            field=models.TextField(max_length=2000),
        ),
    ]
