# Generated by Django 5.0.7 on 2024-09-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brainstorm_tools", "0015_alter_project_detailed_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="rating",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="rating_count",
            field=models.IntegerField(default=0),
        ),
    ]
