# Generated by Django 5.0.7 on 2024-09-29 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brainstorm_tools", "0018_project_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="rating",
            new_name="rating_count",
        ),
    ]
