# Generated by Django 5.0.7 on 2024-09-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brainstorm_tools", "0019_rename_rating_project_rating_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="rating_count",
        ),
        migrations.AddField(
            model_name="projectrating",
            name="rating_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="projectrating",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
    ]
