# Generated by Django 5.0.7 on 2024-09-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brainstorm_tools", "0020_remove_project_rating_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectrating",
            name="rating_count",
        ),
        migrations.AddField(
            model_name="project",
            name="rating_count",
            field=models.IntegerField(default=0),
        ),
    ]
