# Generated by Django 5.0.7 on 2024-09-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brainstorm_tools", "0021_remove_projectrating_rating_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="total_rating",
            field=models.FloatField(default=0),
        ),
    ]
