# Generated by Django 5.0.7 on 2024-10-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brainstorm_tools", "0023_alter_projectrating_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="feature_description",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name="SubFeature",
        ),
    ]
