# Generated by Django 5.0.7 on 2024-10-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brainstorm_tools", "0024_feature_feature_description_delete_subfeature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="feature_description",
            field=models.CharField(default="Text", max_length=300),
        ),
    ]
