# Generated by Django 5.0.7 on 2024-10-02 12:37

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brainstorm_tools", "0025_alter_feature_feature_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("title"),
                name="unique_title_case_insensitive",
            ),
        ),
    ]
